name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Get APT Package Wine
      run: |
        sudo apt-get install -y build-essential &&
        sudo apt-get install -y ninja-build &&
        sudo apt-get install -y meson &&
        sudo apt-get install -y libmozjs-102-dev
      shell: bash

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Meson build
      run: |
        meson build && ninja -C build
