name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read


defaults:
  run:
    shell: bash

jobs:
  ubuntu-build:
    name: Ubuntu Build
    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
      with:
        egress-policy: audit

    - name: Setup Python latest
      uses: actions/setup-python@v4
      with:
        check-latest: true
        cache: 'pip'

    - name: Get Meson
      run: |
        pip install ninja &&
        pip install meson

    - name: Get libmozjs
      run: |
        sudo apt-get install -y libmozjs-102-dev

    - name: Checkout repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    - name: Meson build
      run: |
        meson build && ninja -C build
